modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "separatedleaves"
version = "${version}"
displayName = "Separated Leaves"
authors = "LarsMans"
description = '''
This mod makes leaves only connect to their corresponding log type
'''
#logoFile = ""

[[dependencies.separatedleaves]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.separatedleaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.separatedleaves]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.91,)"
ordering = "AFTER"
side = "BOTH"